Traceback (most recent call last):
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/felicio/.local/share/virtualenvs/odx-pb6_5LxA/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import yaml

with open('../_local_paths.yml') as f:
    paths = yaml.load(f, Loader=yaml.FullLoader)

X = pd.read_pickle(paths['X'])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-2-0d3f667f5ee0>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0myaml[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0;32mwith[0m [0mopen[0m[0;34m([0m[0;34m'../_local_paths.yml'[0m[0;34m)[0m [0;32mas[0m [0mf[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      4[0m     [0mpaths[0m [0;34m=[0m [0myaml[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mf[0m[0;34m,[0m [0mLoader[0m[0;34m=[0m[0myaml[0m[0;34m.[0m[0mFullLoader[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: '../_local_paths.yml'
FileNotFoundError: [Errno 2] No such file or directory: '../_local_paths.yml'

